name: Build and Upload Wheels

on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel cython numpy build

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          build-essential \
          libxext-dev \
          libx11-dev \
          libgl1-mesa-dev

    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      run: |
        brew install cmake
        brew install pkg-config

    - name: Install Windows dependencies
      if: runner.os == 'Windows'
      run: |
        choco install cmake
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        # Install Windows Gaming SDK
        nuget install Microsoft.Windows.Gaming.GDK -Version 1.2.1 -OutputDirectory packages
        # Set environment variable for SDL to find Gaming SDK
        echo "WindowsGamingSDK=$(pwd)\packages\Microsoft.Windows.Gaming.GDK.1.2.1" >> $GITHUB_ENV


    - name: Build wheels
      run: |
        python -m build --wheel

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels-${{ matrix.os }}-${{ matrix.python-version }}
        path: dist/*.whl

  publish:
    needs: build_wheels
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: dist

    - name: Move wheels to dist root
      run: |
        mkdir -p dist_root
        find dist -name "*.whl" -exec mv {} dist_root/ \;

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: dist_root/
