name: Build and Upload Wheels

on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']
        include:
          - os: macos-latest
            python-version: '3.10'
            target: universal2
          - os: macos-latest
            python-version: '3.11'
            target: universal2
          - os: macos-latest
            python-version: '3.12'
            target: universal2
          - os: macos-latest
            python-version: '3.13'
            target: universal2

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel cython numpy build

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          build-essential \
          libxext-dev \
          libx11-dev \
          libgl1-mesa-dev

    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      run: |
        brew install cmake
        brew install pkg-config

    - name: Install Windows dependencies
      if: runner.os == 'Windows'
      run: |
        choco install cmake
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        choco install windows-sdk-10.0
        choco install visualstudio2019-workload-nativegame
        choco install visualstudio2019-workload-universal

    - name: Build wheels
      env:
        MACOSX_DEPLOYMENT_TARGET: "10.15"
      run: |
        if [ "${{ runner.os }}" = "macOS" ]; then
          CFLAGS="-arch x86_64 -arch arm64" CXXFLAGS="-arch x86_64 -arch arm64" python -m build --wheel
        else
          python -m build --wheel
        fi

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels-${{ matrix.os }}-${{ matrix.python-version }}
        path: dist/*.whl

  publish:
    needs: build_wheels
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: dist

    - name: Move wheels to dist root
      run: |
        mkdir -p dist_root
        find dist -name "*.whl" -exec mv {} dist_root/ \;

    - name: Upload combined artifacts 
      uses: actions/upload-artifact@v3
      with:
        name: all-wheels
        path: dist_root/*.whl
